### ISSUE TITLE
Split activity app from activities

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/activity#225]
### Intro
The activity app contains both, the generic logic to store, process and display activities, as well as the activities of the files app.

Similar to the [activity extension of the sharing app](https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/activity.php) the current logic for the sharing, create, delete and other file activities should be done with an activity extension.

### Steps
- [x] In the first step, the two extensions `files` and `files_sharing` are created in the the activity app, containing all processing and display logic of the current activities. #226 
- [x] The extensions are duplicated into the core repository (in case of the files_sharing its merged with the existing extension)
    - [x] Move Sharing extension: https://github.com/owncloud/core/pull/13995
    - [x] Disable Sharing extension in Activity: #232 
    - [x] Move Files extension: https://github.com/owncloud/core/pull/14200
    - [x] Disable Files extension in Activity: #233
- [x] The extensions in the activity app are replaced by minimum versions for testing. #235
- [x] The hooks.php should only contain the "user delete" part. The hooks which are there to trigger the activities should be split into another file and moved to the extension or another file in core. #236

This allows us to check, whether the activity extensions are currently powerful enough, or whether some more methods are needed.
