### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by pmaier1** [owncloud/activity#587]
QA 
- [x] create release branch https://github.com/owncloud/activity/pull/595
- [x] bump version to 2.3.6
- [x] create testplan and test cases Link:  https://github.com/owncloud/activity/issues/592 @davitol 
- [x] test and document in testplan. Final release "Go"

Issues:
- [all QA issues](https://github.com/owncloud/activity/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3AQA%20-label%3Aorga)
- [release blockers](https://github.com/owncloud/activity/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3AQA-blocker%20-label%3Aorga%20)
- [known issues](https://github.com/owncloud/activity/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3AQA-known%20-label%3Aorga%20)

Dependencies:
- 10.0.3

Marketing
- [x] review summary, description https://github.com/owncloud/activity/issues/590
  - description, changelog: https://github.com/owncloud/activity/pull/589 https://github.com/owncloud/activity/issues/590 https://github.com/owncloud/activity/pull/599
  - summary fixed in #595 
- [x] Check screenshots

Build
- [x] Add changelog https://github.com/owncloud/activity/issues/591
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [x] sign and build tarball
- [x] upload to marketplace
- [x] Rename QA milestone to '$version' and close it

**Comment by felixboehm** [comment]
- [ ] Bring back changes in release branch to master branch:
https://github.com/owncloud/activity/pull/595

**Comment by felixboehm** [comment]
Note dependencies
- owncloud min-version="10.0.3" max-version="10.0"

**Comment by PVince81** [comment]
I merged the release branch makefile changes into master.

Ready for release ?

**Comment by PVince81** [comment]
@pmaier1 @DeepDiver1975 ^

**Comment by pmaier1** [comment]
- Added some tasks to OP
- Minor info.xml change https://github.com/owncloud/activity/pull/598
- Proper textual rework postponed to the following release https://github.com/owncloud/activity/issues/590

**Comment by pmaier1** [comment]
After all we got the textual rework in time. Needs review and merge, then we can release the app https://github.com/owncloud/activity/pull/599

**Comment by pmaier1** [comment]
Ready for release
