### ISSUE TITLE
Add acceptance tests

### ISSUE THREAD

**Issue by PVince81** [owncloud/activity#627]
- [x] bootstrap acceptance test framework #673
- [x] UI test + at least one test implemented #673
- [ ] API test + at least one test implemented (suggesting https://github.com/owncloud/activity/issues/613)

**Comment by phil-davis** [comment]
See #659 also - probably move the existing CI to drone and then add the acceptance test infrastructure.
