### ISSUE TITLE
Tracking testing results Activity 2.3.7

### ISSUE THREAD

**Issue by davitol** [owncloud/activity#629]
## 'Activity' Test Plan

Results for Release branch https://github.com/owncloud/activity/tree/release-2.3.7

- Run Testplan with all checked notifications in Activity settings menu and a mail set in our oC server.

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable Activity app via CLI using ```occ app:enable activity``` | The apps gets enabled | ✅   |
Disable Activity app via CLI using ```occ app:disable activity``` | The apps gets disabled | ✅  |
**All activities section** |  |   |
|  |   |
Check that all activities done in this Testplan are shown in this section |  | ✅  |
**Activities by you section** |  |   |
|  |   |
Check that all activities done with my user in this Testplan are shown in this section |  | ✅  |
**Activities by others section** |  |   |
Check that all activities done dealing with my user by other users in this Testplan are shown in this section |  | ✅  |
An LDAP user shares a file with my user | Check that LDAP username is shown properly in this section | ✅  |
An LDAP user edits a file shared with my user | Check that LDAP username is shown properly in this section | ✅    |
A Shibboleth user shares a file with my user | Check that Shibboleth username is shown properly in this section | :construction:  |
A Shibboleth user edits a file shared with my user | Check that Shibboleth username is shown properly in this section | :construction:  |
**Favorites section**|  |   |
|  |   |
Make favorite a file | Check that the notification is shown in activity section and in the sidebar | ❌   |
Make favorite a folder | Check that the notification is shown in activity section and in the sidebar | ❌   |
**Comments**|  |   |
|  |   |
Make a comment in a file | Check that the notification is shown in activity section and in the sidebar | ✅   |
Make a comment in a folder | Check that the notification is shown in activity section and in the sidebar | ✅   |
**Shares section**|  |   |
|  |   |
Share a file/folder | Check that the notification is shown in activity section and in the sidebar| ✅  |
Share a file/folder with a user of other oC server | Check that the notification is shown in activity section and in the sidebar| ❌   | https://github.com/owncloud/activity/issues/623
Share a file/folder via link | Check that the notification is shown in activity section and in the sidebar| ✅  |
Receive a share for another user| Check that the notification is shown in activity section and in the sidebar| ✅   |
Receive a share for another user of other oC server| Check that the notification is shown in activity section and in the sidebar| ❌   | https://github.com/owncloud/activity/issues/623
Receive a file/folder via link adding to your owncloud| Check that the notification is shown in activity section and in the sidebar| ❌  | https://github.com/owncloud/activity/issues/623
**Settings section stream**|  |   |
|  |   |
Uncheck a new file or folder has been created stream notification and create a folder| Notification is not shown | ✅  |
Uncheck a file or folder has been changed stream notification and change a file| Notification is not shown | ✅  |
Uncheck limit notifications about creation and changes to your favorite files stream  notification and change favorite file and a regular file| Notification is not shown | ✅  |

**Comment by davitol** [comment]
- [ ] Add html template to activity email notification https://github.com/owncloud/activity/pull/620
- [ ] https://github.com/owncloud/enterprise/issues/2510

**Comment by davitol** [comment]
**Known issues**
- [ ] Thumbnails of images are not shown in activity menu https://github.com/owncloud/activity/issues/630

**Comment by PVince81** [comment]
@davitol the issue was fixed

**Comment by PVince81** [comment]
damn, the fix went to master, not release branch

**Comment by davitol** [comment]
> damn, the fix went to master, not release branch

Tested and it is solved
