### ISSUE TITLE
write more acceptance tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/activity#677]
main framework is set up for tests (#673, #676), but a lot of cases are still untested

### WebUI
- [x] Creation of new files/folders (#680)
- [x] Update files/folders (#681)
- [x] Delete/Restore files/folders (#685)
- [x] Sharing files/folders ( ~issue: #684~ ) (#686)
- [x] Sharing files/folders from another server ( #689)
- [x] Commenting #688 
- [x] Tagging #688, #691 
- [x] Deleting tags https://github.com/owncloud/activity/pull/699
- [x] Downloading from public links ( #689)
- [ ] Changes to favourites files/folders [Blocked #543]
- [x] Limit own activities to not show up https://github.com/owncloud/activity/pull/686 
- [x] Limiting other activities types and check if it appears or not https://github.com/owncloud/activity/pull/686
- [x] Check activities added by other apps 
  - [x] Ransomware Protection https://github.com/owncloud/ransomware_protection/pull/171
  - [x] files_antivirus https://github.com/owncloud/files_antivirus/pull/297
  - [x] files_texteditor https://github.com/owncloud/files_texteditor/pull/285
  - [x] firewall https://github.com/owncloud/firewall/pull/567
- [ ] ~~Administrative logs~~

### API
- [x] there is no public API, using the private API for some general listing tests https://github.com/owncloud/activity/tree/master/tests/acceptance/features/apiActivity

**Comment by skshetry** [comment]
Noticed a failure in the PR #33994. But many scenarios are failing. Not related perhaps.
```
--- Failed scenarios:
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:69
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:89
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:109
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:129
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:151
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:231
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:260
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:272
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:281
    /drone/src/tests/acceptance/features/webUISharingExternal/federationSharing.feature:292
```
If this happens again, let's reopen this issue.

**Comment by individual-it** [comment]
don't know what `Administrative logs` is about, rest is done
closing for now, please reopen if something is missing
