### ISSUE TITLE
Tracking Testing results for Activity 2.5.0

### ISSUE THREAD

**Issue by davitol** [owncloud/activity#742]
## 'Activity' Test Plan

- Run Testplan with all checked notifications in Activity settings menu and a mail set in our oC server.

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable Activity app via CLI using ```occ app:enable activity``` | The apps gets enabled | ✅   |
Disable Activity app via CLI using ```occ app:disable activity``` | The apps gets disabled | ✅   |
**All activities section** |  |   |
|  |   |
Check that all activities done in this Testplan are shown in this section |  | ✅  |
**Activities by you section** |  |   |
|  |   |
Check that all activities done with my user in this Testplan are shown in this section |  | ✅   |
**Activities by others section** |  |   |
Check that all activities done dealing with my user by other users in this Testplan are shown in this section |  | ✅  |
An LDAP user shares a file with my user | Check that LDAP username is shown properly in this section | ✅  |
An LDAP user edits a file shared with my user | Check that LDAP username is shown properly in this section | ✅ |
**Favorites section**|  |   |
|  |   |
Make favorite a file. Share the file with other user| Check that the notification is shown in activity section and in the sidebar | ❌    |
Make favorite a file. Comment the file | Check that the notification is shown in activity section and in the sidebar | ❌   |
Make favorite a folder. Delete the file | Check that the notification is shown in activity section and in the sidebar | ✅    |
**Comments**|  |   |
|  |   |
Make a comment in a file | Check that the notification is shown in activity section and in the sidebar | ✅ |
Make a comment in a folder | Check that the notification is shown in activity section and in the sidebar | ✅  |
**Shares section**|  |   |
|  |   |
Share a file/folder | Check that the notification is shown in activity section and in the sidebar| ✅ |
Share a file/folder with a user of other oC server | Check that the notification is shown in activity section and in the sidebar| ❌  | https://github.com/owncloud/activity/issues/623
Share a file/folder via link | Check that the notification is shown in activity section and in the sidebar| ✅  |
Receive a share for another user| Check that the notification is shown in activity section and in the sidebar| ✅  |
Receive a share for another user of other oC server| Check that the notification is shown in activity section and in the sidebar| ❌   | https://github.com/owncloud/activity/issues/623
Receive a file/folder via link adding to your owncloud| Check that the notification is shown in activity section and in the sidebar| ❌  | https://github.com/owncloud/activity/issues/623
**Settings section stream**|  |   |
|  |   |
Uncheck a new file or folder has been created stream notification and create a folder| Notification is not shown | ✅ |
Uncheck a file or folder has been changed stream notification and change a file| Notification is not shown |✅ |
Uncheck limit notifications about creation and changes to your favorite files stream  notification and change favorite file and a regular file| Notification is not shown | ✅  |

**Comment by davitol** [comment]
### Changelog Testing Results

### Fixed

- [ ] Error handling when a group no longer exists [#738](https://github.com/owncloud/activity/pull/738)

### Changed

- [ ] Icons renamed to be adblock-friendly [#728](https://github.com/owncloud/activity/pull/728)

### Removed

- [ ] Dropped php 5.6 support [#718](https://github.com/owncloud/activity/pull/718)

**Comment by davitol** [comment]
### Email section
- [ ] A new file or folder has been created
- [ ] A file or folder has been changed
- [ ] A file or folder has been deleted
- [ ] A file or folder has been restored
- [ ] A file or folder has been shared
- [ ] A file or folder was shared from another server
- [ ] A public shared file or folder was downloaded
- [ ] Comments for files
- [ ] System tags
