### ISSUE TITLE
Activity - 2.5.3

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/activity#836]
### Reason

- [x] Release needed for https://github.com/owncloud/activity/pull/833
- [x] https://github.com/owncloud/activity/pull/842

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" https://github.com/owncloud/activity/issues/839

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs. https://github.com/owncloud/docs/issues/2388

### Marketing

- [x] Ping @owncloud/marketing
- [x] Ping pmaier to check `info.xml` description and screenshot

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => https://github.com/owncloud/activity/issues/839 @davitol 

#### Final

- [x] Check that no documentation issues are pending https://github.com/owncloud/docs/issues/2388
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
@davitol RC1 available in https://github.com/owncloud/activity/releases/tag/v2.5.3RC1

**Comment by HanaGemela** [comment]
Put back to dev to fix also Reason https://github.com/owncloud/activity/pull/842

**Comment by HanaGemela** [comment]
P1 until RC2 deployed to portal

**Comment by HanaGemela** [comment]
@davitol Please smoke test https://github.com/owncloud/activity/releases/tag/v2.5.3RC2 now

**Comment by davitol** [comment]
> @davitol Please smoke test https://github.com/owncloud/activity/releases/tag/v2.5.3RC2 now

Tested and LGTM.

About Documentation ticket https://github.com/owncloud/docs/issues/2388 `occ system:cron`


 is the command that allows to send notifications ASAP. But It is not a new command and also hasn't the same purpose than `occ activity:send-emails` that flushes the entire queue

**Comment by HanaGemela** [comment]
I've reopened the documentation issue

**Comment by HanaGemela** [comment]
RC2 can be deployed now. Lowering the priority for the rest of the release process

**Comment by HanaGemela** [comment]
Waiting for documentation before publishing (cc @settermjd)
