### ISSUE TITLE
activity 2.5.4

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/activity#879]
### Reason

- Release needed for "ticket X", "feature Y"

### Product approval

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "activity 2.5.4 Testplan" @davitol https://github.com/owncloud/activity/issues/879#issuecomment-671984654

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => https://github.com/owncloud/activity/issues/879#issuecomment-671984654

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
@davitol ready for testing https://github.com/owncloud/activity/releases/tag/v2.5.4RC1

**Comment by davitol** [comment]
## Changelog

### Fixed

- [ ] If object_name empty for file activity, derive file path from filecache info path - [#875](https://github.com/owncloud/activity/issues/875)

**Comment by davitol** [comment]
> @davitol ready for testing https://github.com/owncloud/activity/releases/tag/v2.5.4RC1

@jnweiger @HanaGemela Tarball is QA-ready 🚢 it
